### ISSUE TITLE
Getting KeyError running script

### ISSUE THREAD

**Issue by mrpunkin** [earl553/garminr10dataconverter#3]
- Python 3.8.9
- MacOS Monterey 12.3.1
- Placed script within GOLF directory as directed and ran via Python3 binary without any other arguments.

`
➜ python3 r10_data_converter.py

Traceback (most recent call last):
  File "r10_data_converter.py", line 14, in <module>
    bag = pd.merge(clubdata, clubtypedata, left_on='clubTypeId', right_on='value')
  File "/Users/bryan/Library/Python/3.8/lib/python/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/Users/bryan/Library/Python/3.8/lib/python/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/Users/bryan/Library/Python/3.8/lib/python/site-packages/pandas/core/reshape/merge.py", line 1097, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/Users/bryan/Library/Python/3.8/lib/python/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'value'
`

**Comment by jbstegman3** [comment]
+1

**Comment by KOTTE75** [comment]
+1

Also, if I remove the line

bag = pd.merge(clubdata, clubtypedata, left_on='clubTypeId', right_on='value')

it gets another KeyError on the next line

File "r10_data_converter.py", line 16, in <module>
    simdata = simdata.explode(column=['shots'])
  File "/home/erik/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 8345, in explode
    result = df[columns[0]].explode()
  File "/home/erik/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/erik/.local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 389, in get_loc
    raise KeyError(key)
KeyError: 'shots'

**Comment by angkec** [comment]
I've encountered this problem on MacOS 12.6. And I've found the solution:

Simply add .from_records whenever pandas is creating data frame from an array. i.e. on line  11, 12, 13, 17 & 18, instead of something like:
simdata = pd.DataFrame(pd.read_json(sim_file)['data'].array)

change it to:
simdata = pd.DataFrame.**from_records**(pd.read_json(sim_file)['data'].array)

Then everything works perfectly. 

I'm using Python 3.10, pandas 1.5.1 on MacOS 12.6. Not sure if the same thing happens on other platforms/versions

Reference: https://stackoverflow.com/questions/20638006/convert-list-of-dictionaries-to-a-pandas-dataframe. (I'm not a pandas developer but a Python developer. Not sure why creating dataframe failed in this case but DataFrame.from_records didn't)

**Comment by dnamnath** [comment]
Almost got it working, thanks angkec! I get an error on the pd.merge : **KeyError: 'clubId'**

t = pd.merge(t, bag, left_on='clubId', right_on='id')

Best I can tell there is no 'clubId' in the t dataframe.  Any help on this?
